#!/usr/bin/env python3
# ALTER — SCRIPT_ACTS generator.
#
# The copy is David's and it will keep moving. So the script blocks are NOT hand-typed into app.js:
# they are GENERATED from _design-sync/stacks-2026-09-20/BLOCKS.txt into the one guarded region
#     // @GEN:SCRIPT_ACTS begin  …  // @GEN:SCRIPT_ACTS end
# next to MED_V2. Edit BLOCKS.txt, re-run this, ship. Never hand-edit the region.
#
#   usage:  python3 _dev/gen-script-acts.py            # rewrite the region in app.js
#           python3 _dev/gen-script-acts.py --print    # print the region, touch nothing
#
# BLOCKS.txt rows are `BLOCK|tier|gap|text`.
#   * `REST|1|SCAN|` (empty text, gap == SCAN) = "the approved body scan goes here" — it becomes a
#     REF entry {ref:"MED_V2", from:9, to:20}, NOT copied strings, so the scan keeps sharing MED_V2's
#     recorded clips and any future edit to the sit reaches every stack that borrows it.
#   * A NON-NUMERIC gap that is not a REF placeholder is a ROLE (David on device 2026-09-20, the spoken-breathing law):
#     `T` = teach line, `C` = short cue said over one exhale, `E` = end line after the wave stops. A role row emits gap 0
#     and its letter into a parallel `role:` array; composeScriptBreathAct reads the roles and computes the real timing
#     from the breath pattern itself, so a breathing block never carries hand-typed silences. Numeric gaps keep role "".
#   * refs live in their own `refs:` field with a `pos` (the seq index they sit in front of) because
#     _dev/gen-voice-11labs.py extracts every string of a flat `seq:[…]` — a nested object inside seq
#     would break that match and the block's lines would silently lose their voice clips.

import os, re, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "_design-sync", "stacks-2026-09-20", "BLOCKS.txt")
APP = os.path.join(ROOT, "app.js")
BEGIN = "  // @GEN:SCRIPT_ACTS begin"
END = "  // @GEN:SCRIPT_ACTS end"

# the shared clips a SCAN placeholder resolves to: MED_V2 seq 9..20 with their MED_V2_GAP values
REFS = {"SCAN": ("MED_V2", 9, 20)}
ROLES = {"T", "C", "E"}          # teach / cue / end — the breath blocks' gap column
NUM = re.compile(r"^\d+(\.\d+)?$")


def esc(s):
    return s.replace("\\", "\\\\").replace('"', '\\"')


def parse(path):
    order, blocks = [], {}
    with open(path, encoding="utf-8") as fh:
        for n, raw in enumerate(fh, 1):
            line = raw.rstrip("\n")
            if not line.strip() or line.lstrip().startswith("#"):
                continue
            parts = line.split("|", 3)
            if len(parts) != 4:
                sys.exit("BLOCKS.txt line %d is not BLOCK|tier|gap|text: %s" % (n, line))
            bid, tier, gap, text = parts[0].strip(), parts[1].strip(), parts[2].strip(), parts[3].strip()
            if bid not in blocks:
                blocks[bid] = {"seq": [], "gap": [], "tier": [], "role": [], "refs": []}
                order.append(bid)
            B = blocks[bid]
            if gap in REFS:
                if text:
                    sys.exit("BLOCKS.txt line %d: a %s placeholder must carry no text" % (n, gap))
                src, a, b = REFS[gap]
                B["refs"].append({"pos": len(B["seq"]), "ref": src, "from": a, "to": b, "tier": int(tier)})
                continue
            if not text:
                sys.exit("BLOCKS.txt line %d has no text" % n)
            role = ""
            if not NUM.match(gap):
                if gap not in ROLES:
                    sys.exit("BLOCKS.txt line %d: gap must be seconds, a role (%s) or a ref placeholder — got %r"
                             % (n, "/".join(sorted(ROLES)), gap))
                role, gap = gap, "0"
            B["seq"].append(text)
            B["gap"].append(float(gap) if "." in gap else int(gap))
            B["tier"].append(int(tier))
            B["role"].append(role)
    return order, blocks


def render(order, blocks):
    out = [BEGIN,
           "  // GENERATED by _dev/gen-script-acts.py from _design-sync/stacks-2026-09-20/BLOCKS.txt — DO NOT HAND-EDIT.",
           "  // One authored script block per stack act, exactly the MED_V2 shape: `seq` spoken in order, `gap` = the",
           "  // seconds of silence AFTER each line at the base curve, `tier` = 1 always said / 2 said when it fits /",
           "  // 3 the whole block. `refs` splice a SHARED range of another script in at `pos` (the seq index it sits in",
           "  // front of) — the body scan is MED_V2 9-20, borrowed not copied, so it keeps the sit's own recorded clips.",
           "  // `role` (breathing blocks only) = T teach / C cue over one exhale / E end line after the wave stops; those rows",
           "  // carry gap 0 because composeScriptBreathAct derives their timing from the breath pattern, not from the page.",
           "  // composeScriptAct() is the fitter; _dev/gen-voice-11labs.py reads the flat `seq` arrays for the voice bank.",
           "  var SCRIPT_ACTS = {"]
    for bid in order:
        B = blocks[bid]
        key = bid if re.match(r"^[A-Za-z_$][A-Za-z0-9_$]*$", bid) else '"%s"' % bid
        out.append("    %s: { seq: [" % key)
        for s in B["seq"]:
            out.append('      "%s",' % esc(s))
        out[-1] = out[-1][:-1]  # drop the trailing comma
        out.append("    ],")
        out.append("      gap: [%s]," % ", ".join(str(g) for g in B["gap"]))
        line = "      tier: [%s]" % ", ".join(str(t) for t in B["tier"])
        if any(B["role"]):
            line += ", role: [%s]" % ", ".join('"%s"' % r for r in B["role"])
        if B["refs"]:
            line += ", refs: [%s]" % ", ".join(
                '{ pos: %d, ref: "%s", from: %d, to: %d, tier: %d }' % (r["pos"], r["ref"], r["from"], r["to"], r["tier"])
                for r in B["refs"])
        out.append(line + " },")
    out[-1] = out[-1][:-1]
    out.append("  };")
    out.append(END)
    return "\n".join(out)


def main():
    order, blocks = parse(SRC)
    region = render(order, blocks)
    if "--print" in sys.argv:
        print(region)
        return
    with open(APP, encoding="utf-8") as fh:
        src = fh.read()
    if BEGIN not in src or END not in src:
        sys.exit("app.js has no @GEN:SCRIPT_ACTS region — add the two marker lines next to MED_V2 first.")
    head, rest = src.split(BEGIN, 1)
    _, tail = rest.split(END, 1)
    with open(APP, "w", encoding="utf-8") as fh:
        fh.write(head + region + tail)
    lines = sum(len(blocks[b]["seq"]) for b in order)
    refs = sum(len(blocks[b]["refs"]) for b in order)
    roles = sum(1 for b in order for r in blocks[b]["role"] if r)
    print("SCRIPT_ACTS: %d blocks, %d spoken lines, %d refs, %d role rows -> app.js" % (len(order), lines, refs, roles))


main()
